### ISSUE TITLE
Buckets are lost in machines when their chunk is unloaded, and the tarmac cutter stacks more than 64 blocks.

### ISSUE THREAD

**Issue by Catz1301** [Flenix/FlenixRoads#27] opened 2020-07-13 14:56 UTC
One more bug I found is that when you put a bucket of fuel in the tarmac cutter, crusher, road factory, and possibly others, they take the fuel, and give back the empty bucket. That is fine. However, if you don't take it, and the chunk unloads, it seems to lose the bucket.

The second bug for this issue (I don't want to keep bugging you) is that the Tarmac Cutter somehow stacks more than 64 blocks of cut Standard Tarmac.
![2020-07-13_10 55 17](https://user-images.githubusercontent.com/33127788/87319365-896fe780-c4f7-11ea-9cde-716671ee8d42.png)

**Comment by Fureniku** [comment] 2020-09-13 15:23
The stacking bug should be fixed in 1.1.8. However, I can't seem to reproduce the buckets disappearing. Can you see if it still happens for you when only Roads is installed?

**Comment by Fureniku** [comment] 2020-11-20 14:26
Couldn't reproduce and no further info, assumed no longer relevant. Please re-open if you're still experiencing the issue and have more information to contribute.

**Closed as completed by Fureniku** 2020-11-20 14:26 UTC
