### ISSUE TITLE
Tar Distillery isn't producing tar.

### ISSUE THREAD

**Issue by Foruknau** [Flenix/FlenixRoads#11] opened 2019-05-08 18:58 UTC
At least for me, I have a tar distillery next to a road factory (models appear connected visually), the distillery is powered and producing coal coke.

When the distillery is placed alone, it produces 1000 tar/one coal coke, then gets stuck and stops producing, with the red progress bar filling completely on repeat. It doesn't use up any coal when it does this, or make any products.

Connected:
![image](https://user-images.githubusercontent.com/50422805/57400367-4dc5e900-71a1-11e9-93ec-8c240e9acf25.png)
![image](https://user-images.githubusercontent.com/50422805/57400413-6fbf6b80-71a1-11e9-94f2-d5b0c77d70d0.png)
![image](https://user-images.githubusercontent.com/50422805/57400445-836ad200-71a1-11e9-9a04-6b1b8af623ea.png)

Disconnected:
![image](https://user-images.githubusercontent.com/50422805/57400491-9b425600-71a1-11e9-8219-895e10db8e0b.png)

**Comment by Fureniku** [comment] 2019-05-08 21:37
Hmm, it may be something to do with those water buckets – the bucket slots are just another way to add/remove tar. Can you try taking the buckets out and see if that lets it function again?

At any rate this is a bug because the progress bar shouldn’t animate, but the checks for that to animate are much less strict than other checks 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Methlon** [comment] 2019-05-17 00:11
I can reproduce.. placing the road factory next to the tar thinger yields no tar a'tall.

Separate, the tar will produce (but stops at 1000), and can be bucketted, but the road factory does not take in any tar.. and nothing happens.  The tar goes into oblivion, and a stack of cobble remains cobble, a stack of andesite remains andesite.

1.12 of course.

**Comment by MrHelloBye** [comment] 2019-11-16 20:09
I can reproduce as well. All the same details as Methlon except I can't even get the tar to go into oblivion, the Road Factory just doesn't empty the bucket.

**Comment by Fureniku** [comment] 2020-03-04 19:20
This should be fixed in the upcoming version; if you still get it in 1.1 full release (not the current betas) please re-open

**Closed as completed by Fureniku** 2020-03-04 19:20 UTC
