### ISSUE TITLE
Player Stops Ticking when inserting dye to the Paint Mixer (with FTBQuests)

### ISSUE THREAD

**Issue by Sparky200** [Flenix/FlenixRoads#29] opened 2020-08-15 23:44 UTC
```
[16:31:26] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassCastException: com.feed_the_beast.ftbquests.util.FTBQuestsInventoryListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at com.silvaniastudios.roads.blocks.tileentities.paintfiller.PaintFillerContainer.func_75142_b(PaintFillerContainer.java:87) ~[PaintFillerContainer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:424) ~[oq.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2338) ~[amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2292) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:881) ~[oo.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2040) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:851) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) ~[MinecraftServer.class:?]
	... 4 more
```

The game fails to cast FTBQuestsInventoryListener to EntityPlayerMP when you insert dye while having FTBQuests installed. I linked the source code that is throwing the error [here](https://github.com/Fureniku/Furenikus-Roads/blob/master/src/main/java/com/silvaniastudios/roads/blocks/tileentities/paintfiller/PaintFillerContainer.java#L87) and the crash log is above. Hope this can get fixed, because I don't want to remove either of these great mods.

**Comment by Fureniku** [comment] 2020-08-15 23:58
Hmm, a strange one. I think the problem is equally mods to blame. I had assumed that a container listener would always be a player, as it is in Vanilla - while it seems FTBQuests added a new type of listener but doesn't handle this situation.

I'll try and get it fixed tomorrow as if I'm right it'll be incredibly straightforward - would you be able to hop in my Discord server and test out a fix when I make it? Much easier than me having to set up a whole environment and learning how to reproduce it for testing the fix, but I can do that if you're busy.

https://discord.gg/BPzpQk2

**Comment by Sparky200** [comment] 2020-08-16 00:00
Sure, thank you! I will joined the server and help out once you get this fixed!

**Comment by Sparky200** [comment] 2020-08-18 00:50
Any update on this? No rush of course.

**Comment by Fureniku** [comment] 2020-09-13 14:37
This was fixed, just forgot to close the issue :)

**Closed as completed by Fureniku** 2020-09-13 14:37 UTC
