### ISSUE TITLE
Letters disappear

### ISSUE THREAD

**Issue by cAsteroide** [Flenix/FlenixRoads#4] opened 2019-02-13 21:15 UTC
I don't know how to explain well, but when I put some letters on a wall, above 1 level that the floor. I can put any letter, but if I put one next to it, they disappear. 
For example, I place the M, but by placing the I next to it, (to form MI) both letters disappear. 

I've only played it in creative, I haven't tried Survival.

**Comment by Fureniku** [comment] 2019-02-13 21:53
Hi there!

I've just tried this and it seems to be working fine. Can you tell me a few more details?
- What block are you placing them on, and what block is under them?
- Are you placing them directly or using the Paint Gun?
- Which colour is this happening with, or is it all of them?

**Comment by Fureniku** [comment] 2019-03-08 21:37
Closed as unable to reproduce.

**Closed as completed** 2019-03-08 21:37 UTC

**Comment by TheDeviantCrafter** [comment] 2019-10-18 15:50
I can confirm that this is an issue in 1.0.2.1. They can be placed on any block, but pop off when they receive a block update.

Placing one letter on a block worlds fine. When you place another letter next to it it pops off.

The issue doesn't occur when placing letters on road blocks from the mod.

Please keep the ability to place letters on any block. It's really nice for building.

**Comment by TheDeviantCrafter** [comment] 2019-10-18 15:54
* I was placing them on the side of a vanilla brick block. 

* By hand

* I tested it with several different shapes, all were affected.

* The issue only happens when placed on walls, not on the tops of blocks.

* The bug did not occur when placed on the top of vanilla blocks.
